name: Build Multiplatform Tunnel
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Install dependencies
        run: flutter pub get

      - name: Build App
        run: |
          flutter create . --platforms=windows,linux,macos
          
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            flutter build windows --release
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            flutter build macos --release
          else
            flutter build linux --release
          fi
        shell: bash

      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: |
          flutter create --platforms=android .
          flutter build apk --release

      - name: List build files (Debug)
        if: matrix.os == 'windows-latest'
        run: dir /s build\windows
        shell: cmd

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: vpn-windows
          path: |
            build\windows\x64\runner\Release\
          if-no-files-found: error

      - name: Upload Linux & Android Artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: vpn-linux-android
          path: |
            build/linux/x64/release/bundle/
            build/app/outputs/flutter-apk/app-release.apk

      - name: Upload macOS Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: vpn-macos
          path: build/macos/Build/Products/Release/*.app
