name: Build Multiplatform Tunnel
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Install dependencies
        run: flutter pub get

      - name: Build App
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            flutter build windows
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Собираем универсальный бинарник для Mac (Intel + Apple Silicon)
            flutter build macos --universal
          else
            flutter build linux
          fi
        shell: bash

      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vpn-prank-${{ matrix.os }}
          path: |
            build/windows/runner/Release
            build/linux/x64/release/bundle
            build/macos/Build/Products/Release
            build/app/outputs/flutter-apk/app-release.apk